theme: jekyll-theme-architect
## Welcome to GitHub Pages

You can use the [editor on GitHub](https://github.com/Monkeyninja5/LPGmain/edit/gh-pages/index.md) to maintain and preview the content for your website in Markdown files.

Whenever you commit to this repository, GitHub Pages will run [Jekyll](https://jekyllrb.com/) to rebuild the pages in your site, from the content in your Markdown files.

<h1 style="color:white">LPG</h1>
<h2 style="color:white">Brandon Kuehn</h2>
<h3 style="color:white">11 May 2022</h3>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  p{text-align: center; color: white}
  
body { 
  background-position: center;
  background-repeat: no-repeat;
  background-size: fill;
  background-image: url("fishing background1.jpg");

  padding: 20px;
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
  color: white;

}

.topnav {
  overflow: hidden;
  background-color: #333;
  width: 460;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}
</style>
</head>
<body>

<ul class="topnav">
  <a class="active" href="index.html">Home</a>
  <a href="Multimediapage.html">Multimedia</a>
  <a href="images.html">Images</a>
  <a href="Links.html">Links</a>
  <a href="MyStory.html">My Story</a>
</ul class="topnav">
<hr>
